### PR TITLE
update bytecount

### PR DESCRIPTION
**Pull request by llogiq**

### CODE REVIEW

**Comment by mattias-p** [comment]
Thank you very much for the PR! May I ask what's changed since 0.2?

**Comment by llogiq** [comment]
Sure. With current rustc, the `[T; 4]` count multiplexing harmed codegen and was no longer needed anyway, so we simplified the algorithm.

**Comment by mattias-p** [comment]
Not to mention the new shiny UTF-8 character counting! I wish there was a changelog for bytecount.

I'll merge this as soon as I get around to test that it actually works. I'm sure there'll be no problems, but you know how it is.

I should add that I did read the bytecount source and I'm very happy I did. That bit twiddling is quite delicious :)

**Comment by mattias-p** [comment]
There. I finally added a unit test.

Thanks again!

**Pull request merged**
